version: '3.5'

services:

  hydroxide:
    build: hydroxide
      context: .
      args:
        HYDROXIDE_VERSION: $HYDROXIDE_VERSION
    ports:
      - 1025
      - 1143
      - 8080
    environment:
      USERNAME: $PROTONMAIL_LOGIN
      PASSWORD: $PROTONMAIL_PASSWORD
      TOKEN: $PROTONMAIL_EXTRA_2FA
      DEBUG: $HYDROXIDE_DEBUG
      INTERPOD: $HYDROXIDE_INTERPOD
    volumes:
     - /root/.config/hydroxide:/root/.config/hydroxide

# add your service here that will integrate with hydroxide
#
# ensure it has the following to receive the auth dat:
#
#   volumes:
#    - hydroxide-volume:/path/on/container
#
# ensure if has the following to properly link to hydroxide's server address:
#
#   links:
#    - hydroxide
#   depends_on:
#    - hydroxide

volumes:
  hydroxide-volume:


