version: '3.5'

services:
  hydroxide:
    image: "${IMAGE_NAME}:${APP_VERSION}"
    container_name:  "${IMAGE_NAME}"
    build:
      context: .
      target: runner
      args:
        APP_VERSION: "${APP_VERSION}"
    restart: "no"
    ports:
      - 1025:1025
      - 1143:1143
      - 8080:8080
    environment:
      EMAIL: "${EMAIL}"
      PASSWORD: "${PASSWORD}"
      TOKEN: "${EXTRA_2FA}"
      DEBUG: "${DEBUG}"
      INTERPOD: "${INTERPOD}"
    volumes:
      - /data/hydroxide:/home/hydroxide/.config/hydroxide
    # networks:
    #   - mail

# networks:
#   mail:
#     name: mail
#     driver: bridge

# add your service that will integrate with hydroxide to this file

# Optional override of user specified in image. Ensure mounted directory grants access to the container user.
#      user: 1000:1000

# ensure it has the following to share networking to be able to access hydroxide
#    networks:
#        - mail

# If your container has a startup dependency on the Hydroxide daemons you can add this
#    depends_on:
#      - hydroxide

# Consider explicitly limiting log sizes - particularly if enabling debug logging.
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
