version: '3.3'

services:

  hydroxide:
    build: hydroxide
    ports:
     - 1025:1025
    environment:
      HYDROXIDEUSER: you@youremail.here
      HYDROXIDEPASS: yourPasswordHere
    volumes:
     - hydroxide-volume:/data

# add your service here that will integrate with hydroxide
#
# ensure it has the following to receive the auth dat:
#
#   volumes:
#    - hydroxide-volume:/path/on/container
#
# ensure if has the following to properly link to hydroxide's server address:
#
#   links:
#    - hydroxide
#   depends_on:
#    - hydroxide

volumes:
  hydroxide-volume:


