version: '3.5'

services:
  hydroxide:
    image: "hydroxide:${HYDROXIDE_VERSION}"
    container_name: hydroxide
    build:
      context: .
      target: runner
      args:
        HYDROXIDE_VERSION: "${HYDROXIDE_VERSION}"
    restart: unless-stopped
    ports:
      - 1025:1025
      - 1143:1143
      - 8080:8080
    environment:
      USERNAME: "${PROTONMAIL_LOGON}"
      PASSWORD: "${PROTONMAIL_PASSWORD}"
      TOKEN: "${PROTONMAIL_EXTRA_2FA}"
      DEBUG: "${HYDROXIDE_DEBUG}"
      INTERPOD: "${HYDROXIDE_INTERPOD}"
    volumes:
      - /data/hydroxide:/home/hydroxide/.config/hydroxide
    networks:
      - mail

networks:
  mail:
    name: mail
    driver: bridge

# add your service that will integrate with hydroxide to this file

# Optional override of user specified in image. Ensure mounted directory grants access to the container user.
#      user: 1000:1000

# ensure it has the following to share networking to be able to access hydroxide
#    networks:
#        - mail

# If your container has a startup dependency on the Hydroxide daemons you can add this
#    depends_on:
#      - hydroxide

# Consider explicitly limiting log sizes - particularly if enabling debug logging.
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
