version: '3.3'

services:

  hydroxide:
    build:
      context: hydroxide
    ports:
      - 1025:1025
      - 1143:1143
      - 8080:8080
    container_name: hydroxide
    environment:
      EMAIL: "${EMAIL}"
      PASSWORD: "${PASSWORD}"
      DEBUG: "${DEBUG}"
      INTERPOD: "${INTERPOD}"
    volumes:
     - /opt/hydroxide-container/data-hydroxide:/home/hydroxide/.config/hydroxide

# add your service here that will integrate with hydroxide
#
# ensure if has the following to properly link to hydroxide's server address:
#
#   links:
#    - hydroxide
#   depends_on:
#    - hydroxide
